#!/usr/bin/env bash
#
# Stands up a throwaway DigitalOcean droplet and writes an inventory pointing at
# it. The droplet is deliberately the smallest size DigitalOcean offers: this
# harness verifies that the provisioning *mechanism* works — rootless daemons,
# lingering, slice limits, port blocks — not that a 1 GB box has usable
# capacity. It does not.
#
#   export DO_SSH_KEY_ID=25208050
#   export DEV_TEST_PUBKEY=~/.ssh/id_rsa.pub
#   ./provision.sh && ./run.sh && ./destroy.sh
#
set -euo pipefail

DROPLET_NAME="devplatform-test"
REGION="sgp1"
IMAGE="ubuntu-26-04-x64"

# s-1vcpu-2gb (≈ USD 0,018/hour), not the smaller s-1vcpu-1gb (≈ USD 0,009).
# 1 GB was tried and does not survive its own provisioning: three rootless
# dockerds plus the registry mirror plus the SDKMAN/pnpm installs exhaust it,
# and with no swap the droplet thrashes into unresponsiveness partway through
# the toolchain role. Do not "optimise" this back down — a run that cannot
# finish costs more than the extra cent per hour.
SIZE="s-1vcpu-2gb"

HERE="$(cd "$(dirname "$0")" && pwd)"

if ! command -v doctl >/dev/null; then
    echo "doctl not found" >&2
    exit 1
fi

if [ -z "${DO_SSH_KEY_ID:-}" ]; then
    echo "DO_SSH_KEY_ID is not set. Available keys:" >&2
    doctl compute ssh-key list >&2
    exit 1
fi

if [ -z "${DEV_TEST_PUBKEY:-}" ]; then
    echo "DEV_TEST_PUBKEY is not set — point it at the public key matching DO_SSH_KEY_ID." >&2
    exit 1
fi

if [ ! -r "${DEV_TEST_PUBKEY}" ]; then
    echo "DEV_TEST_PUBKEY=${DEV_TEST_PUBKEY} is not readable" >&2
    exit 1
fi

if doctl compute droplet get "$DROPLET_NAME" >/dev/null 2>&1; then
    echo "Droplet '$DROPLET_NAME' already exists — destroy it first." >&2
    exit 1
fi

echo "==> Creating $DROPLET_NAME ($SIZE, $IMAGE, $REGION)"
doctl compute droplet create "$DROPLET_NAME" \
    --region "$REGION" \
    --size "$SIZE" \
    --image "$IMAGE" \
    --ssh-keys "$DO_SSH_KEY_ID" \
    --tag-name devplatform-test \
    --wait \
    --format ID,Name,PublicIPv4 \
    --no-header

IP="$(doctl compute droplet get "$DROPLET_NAME" --format PublicIPv4 --no-header)"
if [ -z "$IP" ]; then
    echo "Droplet created but has no public IPv4" >&2
    exit 1
fi

echo "==> Waiting for SSH on $IP"
for _ in $(seq 1 60); do
    if ssh -o StrictHostKeyChecking=no \
           -o UserKnownHostsFile=/dev/null \
           -o ConnectTimeout=5 \
           -o BatchMode=yes \
           "root@$IP" true 2>/dev/null; then
        break
    fi
    sleep 5
done

ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    -o BatchMode=yes "root@$IP" true

cat > "$HERE/inventory/test.ini" <<EOF
; Generated by provision.sh — do not commit.
[dev_boxes:children]
tier0_salvage

[tier0_salvage]
devplatform-test ansible_host=$IP ansible_user=root
EOF

PUBKEY="$(cat "$DEV_TEST_PUBKEY")"
cat > "$HERE/inventory/group_vars/all/roster.yml" <<EOF
---
# Generated by provision.sh — do not commit. Every test person shares the
# operator's key so the harness can log in as each of them.
dev_people:
  alice:
    ssh_keys: ["$PUBKEY"]
  bob:
    ssh_keys: ["$PUBKEY"]
  carol:
    ssh_keys: ["$PUBKEY"]
EOF

echo "==> Inventory written: $HERE/inventory/test.ini ($IP)"
